### ISSUE TITLE
Should type hints for Atom be IAtom?

### ISSUE THREAD

**Issue by snoe** [Tensegritics/ClojureDart#102]
Trying to implement [reagent style cursors](https://github.com/reagent-project/reagent-cursor/blob/master/src/reagent/cursor.cljs) just to see if it'll work and when passed to the flutter helper`widget` `:watch` I receive this error:

```
The following _CastError was thrown building _BodyBuilder:
type 'RCursor' is not a subtype of type 'Atom' in type cast
```

I believe this means that `add-watch` and other atom related functions should be hinted to `IAtom` rather than`Atom` https://github.com/Tensegritics/ClojureDart/blob/81a624a27dad8c9b92856dbb86791013bf11498f/clj/src/cljd/core.cljd#L2055

**Comment by cgrand** [comment]
There should be no type hints at all here. And `add-watch` should just be an inline of `-add-watch`
