### ISSUE TITLE
Can't resolve widgets/InheritedModel

### ISSUE THREAD

**Issue by MarcWeber** [Tensegritics/ClojureDart#110]
Solution:

https://stackoverflow.com/questions/72301239/clojuredart-error-while-host-compiling-ns-samples-tables-require-packagef

No idea why this is required at all.
Happens when running the samples/ eg samples/counter.

Creating new issue so that it can be referenced and be found easily.

Note: If you rerun the init the pubspec.yaml will be overwritten. So you need to readd the missing dependencies.

**Comment by dupuchba** [comment]
Thx for your report @MarcWeber 🙏
