### ISSUE TITLE
Replace "stern warnings"

### ISSUE THREAD

**Issue by cgrand** [Tensegritics/ClojureDart#116]
### Decision
* Default type stays `dynamic`
* `:paramName` in interop calls with named arguments is deprecated in favor of the new syntax`.paramName`. This new syntax allows to syntactically recognize a cll with named arguments without knowing the type of target, thus allowing proper code emission in  the dynamic case.
* `.field` for field access is deprecated in favor of `.-field` which is already supported. This decision follows the same goal as the previous one: allowing good code emission even when types are unknown.

### Original description
"Stern warnings" are way more likely to lead to weird errors than Clojure's reflection warnings, that's why they should be errors.

This is of concern only for interop code. Dynamism of pure Clojure is not affected. It's just about making accidental use of `dynamic` interop (which leads to bizarre error or behaviors) impossible.

Early in ClojureDart development we relied extensively on Dart `dynamic` type because the compiler was completely oblivious to types. Currently we try to avoid relying on the Dart compiler guessing types and try to produce type-explicit code. Dynamic calls used to be the norm, now they are errors.

So here I propose several related changes:
 * default type will now be `Object?` and not `dynamic`
 * in places where `dynamic` semantics would be really wanted the user would have to explicitly write `^dynamic`
 * failure to resolve a member will be be an error unless the target is typed `dynamic`.

**Comment by kennytilton** [comment]
As a dynamic language fan, I am concerned by what seems like a retreat from dynamism. But I hardly know the issues. How much will we be sprinkling around `^dynamic`? Is it _just_ sprinkling, or will we get into situations where the compiler will not want to compile otherwise sensible code, because of strong typing? 

It is hard to guess the impact of such a change from the description. What would the fab example look like marked up as needed under this proposal?

Matrix moves a lot of information around very powerfully in part because it is not judging us by the _declared_ types of things -- will this be a Matrix killer? <gasp> :)

**Comment by cgrand** [comment]
@kennytilton I added this paragraph
> This is of concern only for interop code. Dynamism of pure Clojure is not affected. It's just about making accidental use of `dynamic` interop (which leads to bizarre error or behaviors) impossible.

**Comment by cgrand** [comment]
@kennytilton and to answer your specific question: it wouldn't change a thing for fab.

**Comment by TiLogic** [comment]
I understand the reasons for this proposal, but I worry it will hinder the main reason I love Clojure — the ability start with an idea and iterate on it without worrying about pleasing the compiler.

Currently, Flutter seems to be the reason most developers  (including myself) are using ClojureDart — which is all about interop. Having to figure out the right type hint or add `^dynamic` to code that will change a dozen times before it's ready for use would be unproductive. I do go back and add type hints, but only after the code has stabilized.

Also, how would this affect the usability of a ClojureDart REPL?

**Comment by cgrand** [comment]
@TiLogic good point

What are the problems caused by `dynamic` and how @dupuchba  and I survived them?

Basically the problem is not knowing the type and so not being able to determine if: a member is a field, if a method expects named optionals.
In the past we relied on prefixing properties with `-` (it sill works) and named parameters with the infamous `.&`.

An alternative would be to change how named args are passed: instead of using keywords and blurring lines we could use dot-prefixed symbols: `(m/Duration .milliseconds 250)` instead of `(m/Duration :milliseconds 250)` and emphasize the use of dashes.

**Comment by kennytilton** [comment]
I guess I _am_ worried about interop, because that is where the dynamism can fall down. Not having things as simple as `(let fxtype m/Text] (new fxtype))` means jumping thru a lot of hoops.

Mind you, I am a library author trying to do cool things with _authoring_ dart/flutter, so I am at a sort of meta level where dynamism can be very expressive, and its absence mean a crap ton of boilerplate. :)

**Comment by cgrand** [comment]
@kennytilton could be related to #11 and/or #9. I'm all for dynamism and trying to bring more than Dart offers.

But current dynamism around `dynamic` only delivers frustration.

@dupuchba @kennytilton @TiLogic, new proposal:
* keep `dynamic` as default type
* switch named parameters syntax from `:name` to `.name`: this would make most of the problematic stern warnings innocuous
* on *dynamic* member access without a dash, emit a warning that the compiler can't tell if it's a method or a property : this would make the remaining "bad" case clearer.

Thoughts?

**Comment by TiLogic** [comment]
> Basically the problem is not knowing the type and so not being able to determine if: a member is a field, if a method expects named optionals. In the past we relied on prefixing properties with `-` (it sill works) and named parameters with the infamous `.&`.
> 
> An alternative would be to change how named args are passed: instead of using keywords and blurring lines we could use dot-prefixed symbols: `(m/Duration .milliseconds 250)` instead of `(m/Duration :milliseconds 250)` and emphasize the use of dashes.

Personally, I would prefer with ClojureDart/Dart interop to mirror Clojure/Java as much as possible. Those moving from Clojure would feel at home, and those new to Clojureverse would just see it as the way interop is done.

Thus, I would prefer `(.method instance)` and `(.-property instance)`. I may be in the minority here, but, I also prefer `(Class.)` instantiation for the same reason.

As for named parameters, I'm not sure. I think it would be preferable that something other than `.param val` be to prevent overlapping `(.method instance)`.


A few (not well thought out) ideas:
* use the dispatch character e.g. `#` + `character` (`#:param val` to distinguish it from a keyword?)
* `.-param val` as named parameters are often used to set object properties ???
* an ASCII character not used yet in Clojure like... `|param val`? 😄

**Comment by cgrand** [comment]
@TiLogic
Clojure-style interop is about exposing the host peculiarisms in all their glory and decadence, not about unifying everything.
 
> Thus, I would prefer (.method instance) and (.-property instance). I may be in the minority here, but, I also prefer (Class.) instantiation for the same reason.

The dash is optional in Clojure and is a "recent" addition to help writing CLJC because it's mandatory in CLJS.
By making the dash optional we are following Clojure: don't ask the user to restate something the compiler knows.

> As for named parameters, I'm not sure. I think it would be preferable that something other than .param val be to prevent overlapping (.method instance).

There would be no syntactic overlap as `.method` is in function position only and `.param` can't be in function position.

> use the dispatch character e.g. # + character (#:param val to distinguish it from a keyword?)

Requires reader modification and conflicts with namespaced maps.

> .-param val as named parameters are often used to set object properties ???
Same "false conflict" as for methods.

**Comment by cgrand** [comment]
Trying to summarize the problem:
Currently when the type of the receiver object is unknown we have syntactic ambiguity which leads to compiler guessing the wrong option.

The two ambiguous cases are:
1. `(.f x)` could compile to `x.f` or `x.f()`
2. `(.m x :k v)` could compile to `x.m(CLJD_K, v)` or `x.m(k: v)` 

The first one can be clearly warned about and fixed by a dash without having to research the proper type.

The second one can be fixed by changing the syntax of named parameters. I propose `(.m x .k v)` as `.` always hints to interop features (in old versions of Cljd we had `(.m x .& :k v)`).

**Comment by TiLogic** [comment]
I speak as a humble Clojure user, not a Clojure guru and compiler author, so I think we're looking at this from very different perspectives.

**Comment by cgrand** [comment]
@TiLogic You had a point about dash. In Clojure it can always be determined (either at compile time or runtime) whether a member is a method or a field. So the dash is useless. In ClojureScript, one can never tell so it's mandatory. In ClojureDart, one can't know at runtime so it would be required when the type is unknown but it would put another demand on the user to keep track of which types are known and which are not. Thus to be sure it's better to take the habit to always put the dash for properties.

**Comment by TiLogic** [comment]
@cgrand  I learned to use `.-property` the hard way by ignoring many stern warnings and getting lot's of these! 😆
```
You’re gonna need a bigger boat! 🦈
Error while compiling user/info
...
(try (dart/await (user/info)) (finally (set! cljd.core/-DYNAMIC-BINDINGS bindings__8078__auto__)))
```
