### ISSUE TITLE
`cljd.flutter.alpha2` (was: Support `State.didUpdateWidget` lifecycle method in cljd.flutter.alpha)

### ISSUE THREAD

**Issue by cgrand** [Tensegritics/ClojureDart#122]
The `:watch` option is going to be retrofitted to be used like this:
```
:watch [x an-atom
        y a-future
        :or false
        z a-stream]
```

`x`, `y` and `z` will be rebound each time their atom/future/stream is updated/completed.

These pieces of state will respect the didUpdateWidget lifecycle method.

**Comment by dupuchba** [comment]
I think I'll have the time this week-end to try this design but theoretically this should fix streaming bugs

**Comment by cgrand** [comment]
The one big macro is getting a bit complex to master as a user.

Let's recap what's going on: 
* ordering between the different options is not clear
* > In [didUpdateWidget](https://api.flutter.dev/flutter/widgets/State/widgets/State/didUpdateWidget.html) unsubscribe from the old object and subscribe to the new one if the updated widget configuration requires replacing the object.
* state vs watch

The second point needs more explanation : in stateful widgets we create resources which are almost by definition identities (if you create two controllers or two futures from the same arguments you'll get two non-equal objects). This has two problems:
* You can't compare and thus know if you need to invalidate current resource
* You may end sending one request (or any sort of side effect) per rebuild!

The biggest problem is thus ensuring we don't make easy to write code like:
```
(f/widget
  (let [fut (http/post "...." .body {"launch" "rockets"})]
    (f/widget :watch [resp fut] ...)))
```
or more insidious
```
(f/widget
  (f/widget :watch [resp (http/post "...." .body {"launch" "rockets"})] ...))
```

we don't want to have rebuilds of the outer widget to cause more rockets to be sent.
Side effects should only occur in response to IO (which includes user activity) not as part of the build. 

However maybe I'm just fighting windmills: Flutter just relies on users reading the doc (*cough*)
> The [future](https://api.flutter.dev/flutter/widgets/widgets/FutureBuilder/future.html) must have been obtained earlier, e.g. during [State.initState](https://api.flutter.dev/flutter/widgets/widgets/State/initState.html), [State.didUpdateWidget](https://api.flutter.dev/flutter/widgets/widgets/State/didUpdateWidget.html), or [State.didChangeDependencies](https://api.flutter.dev/flutter/widgets/widgets/State/didChangeDependencies.html). It must not be created during the [State.build](https://api.flutter.dev/flutter/widgets/widgets/State/build.html) or [StatelessWidget.build](https://api.flutter.dev/flutter/widgets/widgets/StatelessWidget/build.html) method call when constructing the [FutureBuilder](https://api.flutter.dev/flutter/widgets/widgets/FutureBuilder-class.html). If the [future](https://api.flutter.dev/flutter/widgets/widgets/FutureBuilder/future.html) is created at the same time as the [FutureBuilder](https://api.flutter.dev/flutter/widgets/widgets/FutureBuilder-class.html), then every time the [FutureBuilder](https://api.flutter.dev/flutter/widgets/widgets/FutureBuilder-class.html)'s parent is rebuilt, the asynchronous task will be restarted.

**Comment by cgrand** [comment]
So something like
```
:watch [resp (http/post "" ...)
              :refresh-on expr] ; if expression changes then the watched expression is rerun
```
Which means the`(http/post "" ...)` would go into initState and wouldn't be reevaluated unless `expr` changes.

**Comment by cgrand** [comment]
I wonder about `:with` vs `:watch` too.

Basically `:watch` is akin to `deref`. You can watch something defined in with but the act of watching is tied to the state lifecycle (like `with`)

```
:with [[val :or :not-yet] (http/post "" ...) ; val would bind to the future, [val] to the current value [val fut] would bind both
           :refresh-key expr] ; this one would be rarely used
```

Let's see how this could accommodate streams and atoms...

**Comment by cgrand** [comment]
> ordering between the different options is not clear

I believe the only possible answer is to follow user order.

**Comment by cgrand** [comment]
`:key` only as first
`:with` introduces disposable resources,, options: `:dispose` `:refresh-on`
`:watch` bind the current value and rebuilds on change, options `:or` `:refresh-on`
`:let` nothing special
`:inherit` no change

**Comment by cgrand** [comment]
To give a more detailed example of `:watch` would work
```
(f/widget
  :watch [v stream
                :or :placeholder
                :refresh-on stream]
   ; here v will be successively tied to each value of stream (and to :placeholder before any value shows up)
   ; if the value of stream changes then the subscription is redone on the new stream
)
```
