### ISSUE TITLE
LSP?

### ISSUE THREAD

**Issue by perpen** [Tensegritics/ClojureDart#127]
As a flutter beginner, I would like to have access to the flutter docs and completion from kakoune.
But obv clojure-lsp doesn't understand things like `["package:flutter/material.dart" :as m]`.

Why can't we use a more standard symbol instead of a string? Some variant of `[dart.flutter.material :as m]`.
Then we could have a simple program translating the dart libs into dummy clojure ones, preserving only the declarations and docstrings, making them available to clojure-lsp as normal.

I thought of other solutions (eg implement a small "proxy" lsp making on the fly transformation before passing code to clojure-lsp), but they're all more complicated.

However I am not too familiar with any of these techs, I may be missing something.

**Comment by Liverm0r** [comment]
There were 2 discussions about this subject on Slack, latest [one](https://clojurians.slack.com/archives/C03A6GE8D32/p1656924382140199) and [previous](https://clojurians.slack.com/archives/C03A6GE8D32/p1655753998558579).

**Comment by perpen** [comment]
Thanks @Liverm0r  - thinking again, my idea of generating clojure stubs for the dart symbols isn't that great, as it would prevent you from going to the actual dart code, which you may want to do sometimes.
And I didn't know about this slack!

**Comment by cgrand** [comment]
> Why can't we use a more standard symbol instead of a string? Some variant of [dart.flutter.material :as m].

Because Dart lib ids are pretty open in their format. It's already common to have relative paths etc.

**Comment by perpen** [comment]
Thanks @cgrand - forgive my naivety!

**Comment by dupuchba** [comment]
@perpen should I close this one ?

**Comment by perpen** [comment]
Sure, but it would be nice to have an idea of the current plans, maybe see some code.
I'm possibly too demanding.

**Comment by perpen** [comment]
I just saw the NEWS.md, my curiosity is satisfied now, closing.
