### ISSUE TITLE
requiring clojure library via host-ns does not work without equivalent dart require 

### ISSUE THREAD

**Issue by aleedmanath** [Tensegritics/ClojureDart#129]
I would expect requiring a clojure lib by itself to compile:
```clj
(ns example
  (:host-ns (:require [clj-lib.core :as lib])))
```

But this will throw `unknown symbol` error when used inside a macro.

A dart shim for the library seems to be required:
```clj
(ns example
  (:require [clj-lib.core :as lib])
  (:host-ns (:require [clj-lib.core :as lib])))
```

I was looking at your usage of macros in codebase and looks like this is perhaps why it's working for you guys
https://github.com/Tensegritics/ClojureDart/blob/6e4e3ba3f9b193c3ffea9eb461c92d929d63a4fa/clj/src/cljd/flutter/alpha.cljd#L5-L7

**Comment by aleedmanath** [comment]
I originally tried `:clj` conditional literal but @dupuchba let me know about `:host-ns`

I understand these may be temporary solutions, I'm just reporting what I bump up against while porting some logic I was using with RN in CLJS

**Comment by cgrand** [comment]
I'm going to chastise @dupuchba  then!

**Comment by dupuchba** [comment]
I am pretty sure @aleedmanath would have find out, I bought him time !

**Comment by aleedmanath** [comment]
I've appreciated the temporary workaround 😼 

given that this usage is temporary, closing in favor of https://github.com/Tensegritics/ClojureDart/issues/128
