### ISSUE TITLE
unable to run dynamic widgets referenced from another namespace

### ISSUE THREAD

**Issue by aleedmanath** [Tensegritics/ClojureDart#133]
sorry for all the issues – i'm porting a hiccup compiler I was using with RN in CLJS to ClojureDart so bumping against all the nooks and crannies!

for this specific issue, the use-case is to be able to declare widgets dynamically.

minimal example: 
```clj
(def column widget/Column)

(def ^:macro-support mappings
;; can't declare 'widget/Column since symbol may not be defined in another namespace, so we use our declaration above
  {:column `column})

(defmacro text [msg]
  `(material/Text ~msg))

(defmacro example-view []
   ;; note: neither '~ or ~ variations worked below
  `('~(get mappings :column)
    .children [(text "works?!")]))
```

this compiles with CLJD watcher but while running flutter results in an error that looks something like this
```
lib/cljd-out/reso/main.dart:78:51: Error: Too few positional arguments: 2 required, 0 given.
return (($if_$1 as lcoc_core.IFn$iface).$_invoke$2(children: $1, ));
```

I'm not sure what's not being transpiled properly, and if it's a mistake on my side or current bug in compilation.

Here is a reproduction below: 
reproduction: https://github.com/aleedmanath/repro-cljd-macros-err/tree/main/repro/dynamic-expr

**Comment by cgrand** [comment]
Have you tried ``widget/Column` it expands to a uniquely qualified symbol usable in all namespaces?

**Comment by aleedmanath** [comment]
```
(def ^:macro-support mappings
  {:column ``widget/Column})

(defmacro text [msg]
  `(material/Text ~msg))

(defmacro example-view []
  (println (get mappings :column))
  ;; note: neither '~ or ~ alone work below
  `(~(get mappings :column)
    .children [(text "works?!")]))
```

Results in 
```
lib/cljd-out/example/main.dart:16:48: Error: Too few positional arguments: 2 required, 0 given.
$if_$1=((f$1 as lcoc_core.IFn$iface).$_invoke$2(children: $1, ));
```

If I changed `~(get mappings :column)` to quoting the symbol `'~(get mappings :column)` then results in
```
lib/cljd-out/example/main.dart:14:38: Error: The method '$_invoke$2' isn't defined for the class
'PersistentList<dynamic>'.
 - 'PersistentList' is from 'package:dynamic_expr/cljd-out/cljd/core.dart' ('lib/cljd-out/cljd/core.dart').
Try correcting the name to the name of an existing method, or defining a method named '$_invoke$2'.
final f_material.Widget? cast$1=(($2.$_invoke$2(children: $1, )) as f_material.Widget?);
```

**Comment by dupuchba** [comment]
if you inline it it will work
```
(def ^:macro-support mappings
  {:column `widget/Column})
```

**Comment by aleedmanath** [comment]
I'm not sure what's different in above snippet, but I don't think it'll work 

there's a reproduction above if you'd like to confirm whether this is an issue 

one technique I was using in CLJS is to reference the JS ns object with the mappings at at runtime, I can try to see if some variation of that works here

**Comment by aleedmanath** [comment]
Yeah that doesn't work either. Still learning to get visibility into system and distinguish different environments (Clojure, Dart, Flutter) but I don't think error is on my side.

```clj
(def mappings
  {:column widget/Column})

(defmacro text [msg]
  `(material/Text ~msg))

(defmacro example-view []
  `((get mappings :column)
    .children [(text "works?!")]))
```

Results in
```
lib/cljd-out/example/main.dart:16:48: Error: Too few positional arguments: 2
required, 0 given.
$if_$1=((f$1 as lcoc_core.IFn$iface).$_invoke$2(children: $1, ));
```
@dupuchba  It looks like it's being parsed as a fn with 2 positional arguments (`$_invoke$2`) rather than 1 named parameter 
resulting in a error (from Fart?) when it compiles code itself?

**Comment by dupuchba** [comment]
hey @aleedmanath, sorry I missed your response and then I went on holidays, do you still need help ?

**Comment by aleedmanath** [comment]
i took a pause as well so not sure :) 

i do think this is a problem unless there's a mistake in reproduction or snippets above

but if you like we can close and re-address if/when it comes up

**Comment by aleedmanath** [comment]
going to close and if need be reopen later
