### ISSUE TITLE
Generate a better `.gitignore` when initializing a project

### ISSUE THREAD

**Issue by mynomoto** [Tensegritics/ClojureDart#148]
I think the current one doesn´t ignore as much as it could. Something like https://github.com/Tensegritics/ClojureDart/commit/83a8381c7741565ab2af97ab735d5e96e9137b2c maybe but less aggressive because people could use flutter/dart dependencies and want their `pubspec.yaml`.

**Comment by cgrand** [comment]
Something like?
```
android/*
ios/*
lib/cljd-out
linux/*
macos/*
test/cljd-out
web/*
windows/*
```

Not sure about ignoring all the `platform/*`

**Comment by mynomoto** [comment]
I think that for simple projects it is safe to remove `platform/*` but not really sure if there can be custom code there.
Mine is currently:
```
*.class
*.jar
*.log
*.swp
.clj-kondo/**/
.clojuredart/
.cpcache/
.dart_tool/
.lsp/.cache/
.packages
android/
build/
ios/
lib/
linux/
macos/
web/
windows/
```
It is on the aggressive side since after cloning I need to run `clojure -M:cljd init` after cloning before I can use `clojure -M:cljd flutter`

**Comment by TiLogic** [comment]
[Deep linking](https://docs.flutter.dev/development/ui/navigation/deep-linking) and many popular packages require modifying platform code, so leaving `platform/*` out of the `.gitignore` might be a good idea.

**Comment by cgrand** [comment]
Going to use this one as a basis https://raw.githubusercontent.com/flutter/flutter/master/.gitignore

**Comment by grav** [comment]
How about `lib/main.dart`?

**Comment by cgrand** [comment]
I pushed (ebef22458ae5d333b2e93b92abe0a92cc33e0978) a very conservative take: just adding Clojure/ClojureDart ignores and not touching anything related to Flutter.
The rational being that Flutter .gitignore correctly does its job and we have no clue in further excluding flutter specific stuff.
