### ISSUE TITLE
Hot reload / restart doesn't work

### ISSUE THREAD

**Issue by rlhk** [Tensegritics/ClojureDart#149]
Just briefly trying out ClojureDart by following the first app code in main readme. 
Able to run the simple app in iPhone simulator, macOS and Chrome.

The Flutter runner for iOS app is launched like `clj -M:cljd flutter -d "iPhone 13"`
The issue is that when I change the text Widget content, both hot reload and hot restart don't work, even though the console shows "Performing hot reload..."
The compiled main.dart code does reflected the change of main.cljd
And apparently the launcher / console doesn't respond to any command, including `r` and `R`. 

NOTE: Auto hot reload works for web app with the same source code.

My env:

`flutter --version`
```
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (7 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
```

`java -version`
```
openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment Homebrew (build 18.0.2.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.2.1+0, mixed mode, sharing)
```

**Comment by adilwahla** [comment]
### do this &  make video of issue if possible 

- in the terminal, run
- flutter doctor -v
- flutter upgrade
- Also, try File > Invalidate Caches / Restart...

**Comment by rlhk** [comment]
> ### do this & make video of issue if possible
> * in the terminal, run
> * flutter doctor -v
> * flutter upgrade
> * Also, try File > Invalidate Caches / Restart...

Will try these soon.

A bit new findings as discussed in Slack: https://clojurians.slack.com/archives/C03A6GE8D32/p1661796793038539
Manually pressing `enter` in console triggers reload.

**Comment by rlhk** [comment]
> ### do this & make video of issue if possible
> * in the terminal, run
> * flutter doctor -v
> * flutter upgrade
> * Also, try File > Invalidate Caches / Restart...

Here's the video. Am using Atom editor, no "File > Invalidate ..."

https://user-images.githubusercontent.com/17818753/187321904-4f1c9127-cef3-45b5-8ff2-644aebe6b8c6.mp4

**Comment by adilwahla** [comment]
### Hey i am not well aware of clojureDart but i followed offcial docx of flutter 
Flutter Documentation says "Hot reload loads code changes into the VM and re-builds the widget tree, preserving the app state; it doesn’t rerun main() or initState()"

So, it looks like if the app logic resides outside the main method, then Hot Reloading works. Try to refactor your app like below and then do Restart (green button). Any subsequent changes you make, will be HOT RELOADED when saved.

like this 

```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text("Demo Project"),
        ),
        body: Center(child: new Text("Hello World!!!")),
      ),
    );
  }
}
```
Note: if you are adding any new assets like images only hot restart will work 

> On top of all make sure you have enabled hot reload in settings of whatever is VS code or android studio 
I hope this will help you :)

**Comment by rlhk** [comment]
Thanks @adilwahla 

I tried the following and the behaviour is still the same. Will try the sample projects and report here.

```clojure
(ns acme.main
  (:require ["package:flutter/material.dart" :as m]))

(defn my-app []
  (m/MaterialApp
    .title "to Flutter"
    .theme (m/ThemeData .primarySwatch m.Colors/pink)
    .home (m/Scaffold
            .appBar (m/AppBar
                      .title (m/Text "ClojureDart"))
            .body (m/Center
                    .child (m/Text "Reload Me!"
                             .style (m/TextStyle
                                      .color m.Colors/red
                                      .fontSize 32.0))))))

(defn main []
  (m/runApp (my-app)))
```

**Comment by rlhk** [comment]
Alright. Auto hot reloading works as expect if I follow the sample project code using `cljd.flutter.alpha`. 

@adilwahla FYI: Whether `home` is in `main` or not doesn't matter

The quick start first app in README.md should be revised like the following ... happy to make a PR if agreed.

```clojure
(ns acme.main
  (:require
    ["package:flutter/material.dart" :as m]
    [cljd.flutter.alpha :as f]))

; Same if this fn is used in main.
(defn home []
  (f/widget
   (m/Scaffold
      .appBar (m/AppBar
                .title (m/Text "ClojureDart"))
      .body (m/Center
              .child (m/Text "Reload"
                       .style (m/TextStyle
                                .color m.Colors/red
                                .fontSize 32.0))))))

(defn main []
  (m/runApp (m/MaterialApp
              .title "Flutter"
              .theme (m/ThemeData .primarySwatch m.Colors/pink)
              ; .home (home))))
              .home (f/widget
                       (m/Scaffold
                          .appBar (m/AppBar
                                    .title (m/Text "Hello ClojureDart"))
                          .body (m/Center
                                  .child (m/Text "Reload..."
                                           .style (m/TextStyle
                                                    .color m.Colors/red
                                                    .fontSize 32.0))))))))
```

**Comment by adilwahla** [comment]
@rlhk please close the issue as successful if you think its resolved only you have right to close

**Comment by rlhk** [comment]
> @rlhk please close the issue as successful if you think its resolved only you have right to close

Oh sure :)
