### ISSUE TITLE
Add in documentation that ClojureDart needs Java 11 for running.

### ISSUE THREAD

**Issue by ianffcs** [Tensegritics/ClojureDart#15]
Using Java 8, I've got this error below:

```
clj -M -m cljd.build init --dart quickstart.helloworld
Syntax error (NoSuchFieldException) compiling . at (cljd/compiler.cljc:959:21).
nullWriter
```

Since java.io.Writer/nullWriter is available only for java > 11 as seen in [javadocs](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/Writer.html#nullWriter()), it's good to add in the [quickstart documentation](https://github.com/Tensegritics/ClojureDart/blob/main/doc/quick-start.md) that Java 11 is required.

**Comment by dupuchba** [comment]
done https://github.com/Tensegritics/ClojureDart/commit/ffcdb85a5dc4c1290e8a5602034b3c9a98a0c403
