### ISSUE TITLE
Problem M1 -  clj -M:cljd init

### ISSUE THREAD

**Issue by josephinoo** [Tensegritics/ClojureDart#159]
`Syntax error (NoSuchFieldException) compiling . at (cljd/compiler.cljc:1011:21).
nullWriter

Full report at:
/var/folders/6k/577gznj96m30s3gn7tg0zd400000gn/T/clojure-1256927317260234910.edn`

**Comment by cgrand** [comment]
You need Java 11+.

**Comment by josephinoo** [comment]
thanks
