### ISSUE TITLE
Assert failed: (= (count args) 1) when trying to compile `(> 4 3 2 1)`

### ISSUE THREAD

**Issue by D00mch** [Tensegritics/ClojureDart#168]
**Describe the bug**
Can't compile simple program, having an error when run:
`clj -M:cljd watch`
```
Execution error (AssertionError) at cljd.compiler/write (compiler.cljc:3822).
Assert failed: (= (count args) 1)
```

Does your problem persist after `clj -M:cljd clean`?
Yes.

**To Reproduce**
Checkout to 0b83ba8dd0bae639f5d457f275d6800eba57ffe4
Try to compile dart hello world with:
```clojure
(ns quickstart.helloworld)
(defn main
  []
  (> 3 2 1 0)
  (print "hello"))
```

**Expected behavior**
Program compiles.

**Additional context**
First appeared here https://github.com/D00mch/DartClojure/issues/17

I found that less than 4 args in `<` work. Working example:
```clj
(ns quickstart.helloworld)
(defn main []
  (> 3 2 1)
  (print "hello"))
```

**Comment by dupuchba** [comment]
The failing assert is the one from the `write` function in compiler.cljc - should be an easy fix but I am too tired
<img width="573" alt="image" src="https://user-images.githubusercontent.com/911705/208186666-150efe01-6426-4a1b-8579-48391b6f4db6.png">
