### ISSUE TITLE
Error extending `StatelessWidget` via `defrecord`

### ISSUE THREAD

**Issue by elliot42** [Tensegritics/ClojureDart#177]
Trying to use `defrecord` to `:extends m/StatelessWidget` creates an override error:

```clojure
(defrecord Text [s]
  :extends m/StatelessWidget
  (build [this ctx]
    (m/Text s)))
```

Produces error:

```
lib/cljd-out/acme/sketch.dart:166:7: Error: Applying the mixin 'MapMixin' to 'StatelessWidget with EqualsEquivMixin' introduces an erroneous override of 'toString'.
Performing hot reload...
class Text<K, V> extends f_material.StatelessWidget with lcoc_core.EqualsEquivMixin, d_collection.MapMixin<K, V>, lcoc_core.ToStringMixin implements lcoc_core.IRecord$iface, lcoc_core.IEquiv$iface, lcoc_core.IMap$iface, lcoc_core.ISeqable$iface, lcoc_core.IAssociative$iface, lcoc_core.ILookup$iface, lcoc_core.ICounted$iface, lcoc_core.ICollection$iface, lcoc_core.IWithMeta$iface, lcoc_core.IMeta$iface, lcoc_core.IKVReduce$iface, lcoc_core.IHash$iface, lcoc_core.IPrint$iface {
      ^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/collection/maps.dart:197:10: Context: The method 'MapMixin.toString' has fewer named arguments than those of overridden method 'Object with Diagnosticable.toString'.
  String toString() => MapBase.mapToString(this);
         ^
../flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3110:10: Context: This is the overridden method ('toString').
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.info }) {
         ^
Try again after fixing the above error(s).
```

See below for an easier way to read the class declaration it generated.

Does your problem persist after `clj -M:cljd clean && flutter clean`?

Yes

**Repro conditions**
- Tested on CLJD 4d67a9c98a6675fec59c8978996196125f0d0990 and 6ad3a19226cfad54e41dc21fd69839f85dcbf08f
- Flutter 3.3.9 and 3.3.10
- `deftype` works

---

Here's the generated class from above with linebreaks:

```
class Text<K, V>
  extends f_material.StatelessWidget with
    lcoc_core.EqualsEquivMixin,
    d_collection.MapMixin<K, V>,
    lcoc_core.ToStringMixin
  implements
    lcoc_core.IRecord$iface,
    lcoc_core.IEquiv$iface,
    lcoc_core.IMap$iface,
    lcoc_core.ISeqable$iface
    lcoc_core.IAssociative$iface
    lcoc_core.ILookup$iface,
    lcoc_core.ICounted$iface,
    lcoc_core.ICollection$iface,
    lcoc_core.IWithMeta$iface,
    lcoc_core.IMeta$iface,
    lcoc_core.IKVReduce$iface,
    lcoc_core.IHash$iface,
    lcoc_core.IPrint$iface {
```

I think the following plain Dart appears to exhibit the same problem (when run with `flutter run`):

```dart
import 'package:flutter/material.dart';
import 'dart:collection';

class Text<K, V> extends
  StatelessWidget with
  MapMixin<K,V> {
}
```

**Comment by cgrand** [comment]
Try adding `(toString [this .minLevel] "test")` to your defrecord.

**Comment by elliot42** [comment]
Manually implementing `toString`

```
(defrecord Text [s]
  :extends m/StatelessWidget
  (build [this ctx]
    (m/Text s))
  (toString [this .minlevel] "test"))
  ```
  
  Results in:

```  
Too many optional named arguments (1 extra(s)) for method toString for StatelessWidget of library package:flutter/material.dart```

**Comment by cgrand** [comment]
One stone two birds... or one report two bugs should I say.

The error you got when adding `(toString [this .minLevel] "test")` is a bug on its own of member lookup. According to the **Dart spec, 10.9 Superclasses**:

> The superclass S′ of a class C whose declaration has a with clause with M1, . . . , Mk and an extends clause extends S is the abstract class obtained by application of mixin composition (12) Mk ∗ · · · ∗ M1 to S. The name S′ is a fresh identifier. If no with clause is specified then the extends clause of a class C specifies its superclass. If no extends clause is specified, then either:
• C is Object, which has no superclass. OR
• Class C is deemed to have an extends clause of the form extends Object,
and the rules above apply.

So mixins should be considered before the explicit superclass because mixins + explicit superclass are considered together as an abstract anonymous class of its own.

I have a patch for this.

**Comment by cgrand** [comment]
Okay, I locally modified `defrecord` to not introduce the `ToStringMixin` when there was an explicit `toString`... only to find that `MapMixin` (which is a standard Dart mixin) defines a 0-arg `toString` method too.

From here I'm not sure how to proceed: implementing our own MapMixin (which wouldn't provide a toString) is a maintenance/compat burden when the Dart team adds methods.

I'm be tempted to label it as a known limitation of defrecord and ask you to implement your own macro around deftype. Maybe you don't need your "records" to also be dart maps.
@elliot42 what's your design intent?

**Comment by elliot42** [comment]
Yeah in practice can likely roll with `deftype`, `reify` or `(f/widget)` for now.

Not 100% sure of it, but was trying to prototype:

1. Model the domain with records
2. Map the domain model to the view by implementing `Widget/build` on model
3. Handle updates using standard `assoc`

Basically if you already have your domain model in a state atom:

```clojure
(def state (atom {:items [(->Item "foo") (->Item "bar")]}))
```

Then using `IAssociative` seems like a natural way to read/write/update the data, and implementing `Widget/build` seems likes a natural way to express how to render/visualize the data.

Stu's REBL talk in particular was a great example of being able to directly render raw data `(build my-map)` without needing to manually hard-couple a specific widget on top of the data `(build (my-map-widget my-map))`: https://www.youtube.com/watch?v=c52QhiXsmyI&t=800s
  
----

Totally separately, the other idea I was pursuing was "how would you model a Widget in plain Clojure?"  In OOP the concept is "an opaque object with private mutable state and a public interface method":

```dart
class ItemWidget {
  var title, completed;
  Widget build(...) { ... }
}
```

My _impression_ was that traditionally in CLJ the same concept is expressed as "the immutable data model plus a function of/on that data" -- i.e. a `defrecord`.  I guess in this case, a `deftype` is more literally the host OOP class, a function closing over values or atoms accomplishes the same thing.  But my understanding was that when possible a higher/CLJ-level record was preferable to a lower/host-level type:

https://clojure.org/reference/datatypes#_why_have_both_deftype_and_defrecord

As far as I know these are not blockers for now for doing useful work!  But those were the concepts/intents.  Thanks so much for investigating.

**Comment by elliot42** [comment]
I can close this for now if it's out of scope / not an issue with `defrecord` per se but the interaction with `Diagnosticable` via `StatelessWidget` -- let me know?

**Comment by cgrand** [comment]
Closing for now
