### ISSUE TITLE
How Can I Cast Object?

### ISSUE THREAD

**Issue by amjil** [Tensegritics/ClojureDart#180]
Like this `renderObject as RenderBox;`
Used clojure's cast method but got Unkown Symbol

**Comment by cgrand** [comment]
Did you try `^alias/RenderBox renderObject`? where `alias` is the alias you used in the require you used for the lib exposing `RenderBox`?

**Comment by cgrand** [comment]
Part of #181

**Comment by amjil** [comment]
Thanks a lot, I will try it later.

**Comment by amjil** [comment]
Close it
