### ISSUE TITLE
False positive clj-kondo: unresolverd symbol in f/widget :watch

### ISSUE THREAD

**Issue by Altariarite** [Tensegritics/ClojureDart#191]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/11803173/218226198-58f6c539-60bc-4d5f-b30f-3ce614d6f479.png">

clj-kondo gives a false positive in the `widget` macro. The enviroment is vscode+calva, with clj-kondo version 2023.01.20

**Comment by Altariarite** [comment]
Thanks for the tags. I can try to do this by looking into clj-kondo hooks maybe

**Comment by Altariarite** [comment]
For reference: looks like the issue is two-fold.
1. The macro name is outdated: `s/cljd.flutter.alpha/cljd.flutter` in https://github.com/Tensegritics/ClojureDart/blob/2d9fe408f859bdcade6bd41f86ff9b2d7cd1fd8f/resources/clj-kondo.exports/tensegritics/clojuredart/config.edn#L14

2. there's something wrong with macro generation that made `clj-kondo` unaware of surrounding `let`

**Comment by D00mch** [comment]
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/14236531/218328831-e66effcf-adff-4e50-b2aa-c7062ed05da3.png">
