### ISSUE TITLE
How should I handle generics types ?

### ISSUE THREAD

**Issue by kmrk** [Tensegritics/ClojureDart#193]
such as in bloc : 

> class AuthBloc extends Bloc<AuthEvent, AuthState> { }

what should **Bloc<AuthEvent, AuthState>** be in ClojureDart?

please help

**Comment by cgrand** [comment]
`#/(Bloc AuthEvent AuthState)` I omitted ns aliases since you didn't provided them.
Have you seen our cheatsheet? https://github.com/Tensegritics/ClojureDart/raw/main/doc/ClojureDart%20Cheatsheet.pdf

**Comment by kmrk** [comment]
Thank you very much! I will carefully read the cheatsheet!
