### ISSUE TITLE
Compilation fails when using future with nullable type without type hint

### ISSUE THREAD

**Issue by straux** [Tensegritics/ClojureDart#195]
**Describe the bug**

Compilation fails when using future with nullable type without type hint.

**To Reproduce**

1. Clone and run https://github.com/straux/cljd-sandbox
2. See this part of the code https://github.com/straux/cljd-sandbox/blob/master/src/mobile_number.cljd#L9-L12

When no type hint is given, we get the following error :

`lib/cljd-out/kazoo/mobile-number.dart:25:9: Error: A value of type 'List<SimCard>?' can't be assigned to a variable of type 'List<SimCard>' because 'List<SimCard>?' is nullable and 'List<SimCard>' isn't.`

**Expected behavior**

The compiler should infer the type without the type hint.

**Comment by dupuchba** [comment]
not yet in update-sha but it will be this week or next week
