### ISSUE TITLE
Any interest in disclosing the source and/or taking contributions before the official release?

### ISSUE THREAD

**Issue by johnmcconnell** [Tensegritics/ClojureDart#2]

**Comment by xlfe** [comment]
Looking forward to it!

**Comment by siliconsorcery** [comment]
I am interested.

**Comment by zikajk** [comment]
Of course!

**Comment by dupuchba** [comment]
Release in 4 days

**Comment by ieugen** [comment]
I am interested! 
I would like build a small app and I was researching the options available for Clojure/Script . 
I decided to postpone until Clojure Dart is out.
The suspense is killing me :) .

**Comment by ieugen** [comment]
I am interested! 
I would like build a small app and I was researching the options available for Clojure/Script . 
I decided to postpone until Clojure Dart is out.
The suspense is killing me :) .
