### ISSUE TITLE
Plain Dart Quickstart compiles the wrong program when project root directory isn't exactly `helloworld`

### ISSUE THREAD

**Issue by PEZ** [Tensegritics/ClojureDart#21]
Hello, thanks for your work with ClojureDart!

This is a follow-up from Clojurians Slack.

When following the instructions for the [Plain Dart Quickstart](https://github.com/Tensegritics/ClojureDart/blob/main/doc/quick-start.md), almost to the letter, I ended up with the wrong program being compiled. It prints `Hello World!`, and not the expected `hello, world`. The only part I didn't follow was that I did not name the project directory `helloworld`.

When I follow the instructions, including naming the project directory `helloworld`, it prints the expected message.

I published a repository containing both variants here: https://github.com/PEZ/clojuredart-quickstart-root-problem

I removed the `.gitignore` files, in case some otherwise ignored file contains some clue.

**Comment by dupuchba** [comment]
I can't reproduce what you are describing.
When you look at both generated dart under `lib/cljd-out/quickstart/helloworld.dart` the code looks great.
Maybe I am missing something

**Comment by PEZ** [comment]
Indeed, that looks fine. But when I run the program I get these results:

```
~/Projects/tests/clojuredart/repro/helloworld % dart run
Building package executable... (1.0s)
Built helloworld:helloworld.
hello, world
```

```
~/Projects/tests/clojuredart/repro/hello-clojurdart % dart run
Building package executable...
Built hello_clojurdart:hello_clojurdart.
Hello world!
```

You don't? Is there some info from my system I should provide that could point at what is making the difference?

**Comment by dupuchba** [comment]
and if you do 
`dart run -t /lib/cljd-out/quickstart/helloword.dart` ?

**Comment by PEZ** [comment]
That gives me an error that `-t` is not an known option. But if I skip the `-t`:

```
~/Projects/tests/clojuredart/repro/hello-clojurdart % dart run lib/cljd-out/quickstart/helloworld.dart
lib/cljd-out/quickstart/helloworld.dart: Warning: Interpreting this as package URI, 'package:hello_clojurdart/cljd-out/quickstart/helloworld.dart'.
hello, world
```

I don't know what I am doing here, totally new to Dart.  😄

**Comment by PEZ** [comment]
The contents of the `bin` directory is quite different between the two:

1. https://github.com/PEZ/clojuredart-quickstart-root-problem/tree/master/hello-clojurdart/bin2. 
   * There's a `bin/hello_clojurdart.dart` here with the code that matches what is executed with `dart run`
   * And also a `bin/hello-clojurdart.dart` which just imports the stuff in `lib`
1. https://github.com/PEZ/clojuredart-quickstart-root-problem/tree/master/helloworld/bin
   * Here only a `bin/helloworld.dart` with the imports.

**Comment by cgrand** [comment]
ah ah it's some dash-munging on the Dart side!
