### ISSUE TITLE
Problem with methods named arguments

### ISSUE THREAD

**Issue by Liverm0r** [Tensegritics/ClojureDart#22]
## The problem
Trying to rewrite code
`router.define("/", handler: rootHandler);`
with 
`(.define router "/" :handler root-handler)`

Having the result:
```bash
lib/cljd-out/minataurus/main.dart:19:37: Error: Too many positional arguments: 1 allowed,
but 2 found.
Try removing the extra positional arguments.
return (UmIcmlcom_main.router.define(const UmIcmlcoc_core.Keyword(null, "handler",
297822107, ), UmIcmlcom_main.root_handler, ));
```

[File](https://github.com/Liverm0r/minataurus/blob/named-arg-bug/src/minataurus/main.cljd) with code.
Library:   [fluro](https://pub.dev/packages/fluro): ^2.0.3

## Reproduce steps
Pushed my current project with the issue.
```bash
git clone https://github.com/Liverm0r/minataurus.git
cd minataurus
clj -M -m cljd.build flutter
```

## Tried
`rm -rf clojuredart` and restart the clj flutter.

**Comment by dspiteself** [comment]
Looks like you forgot to copy the "/" to you clojure version
`(.define router "/" :handler root-handler)`

**Comment by Liverm0r** [comment]
Sory, I forgot to copy "/" only in issue. I tried with "/" first time, here is the initial slack [thread](https://clojurians.slack.com/archives/C03A6GE8D32/p1650145755436399)

**Comment by dupuchba** [comment]
The problem: the compiler does not infer `router`, hence the warning 
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/911705/164006551-2d9e1aee-122a-460a-ad7d-6ff18b8b0d15.png">
The real problem is a design choice we had to make. @cgrand will be free this afternoon to explain.

The fix (2 choices)
1/ `(.define ^fluro/FluroRouter router "/" :handler root-handler)` tag when you use `router`
2/ `(def ^fluro/FluroRouter router (fluro/FluroRouter.))` tag the `def`

**Comment by cgrand** [comment]
Brain dump on this behavior:
- Core issue `(def x (constructor....))` x is `dynamic`
    - or more generally the inference of the expression doesn't transfer to the var
    - thus the user has to type hint the var itsef
- Why is it like that?
    - Because so does Clojure
    - Because if you redef and that the inferred type change you have to recompile every code referring this var (and this may cascade) thus promising nothing is easier.
- Right now we transitively recompile all dependants so we could transfer the inferred type without adding complexity. It will impact REPL design though, maybe stick to a broadly sweeping dependants recompilation for REPL too.
- Conceptually the inferred type may be too precise when you think of types as contracts.
