### ISSUE TITLE
clj-kondo error when annotating ^bool

### ISSUE THREAD

**Issue by dancojocaru2000** [Tensegritics/ClojureDart#221]
When trying to annotate a let binding with `^bool`, as in the example below, I get the following error from clj-kondo: "Unresolved symbol: bool"

```clojure
(let [x ^bool (.contains (. train "[]" "number") (.-text search-text))] x)
```

Compiling the code itself works.

**Comment by cgrand** [comment]
Is there anything we can do in ClojureDart proper to fix that or is this more of a Kondo issue?

**Comment by D00mch** [comment]
https://github.com/Tensegritics/ClojureDart/pull/224

**Comment by cgrand** [comment]
@D00mch thanks! your are our condo hero! 🙏
