### ISSUE TITLE
,can't compile the Hello Sample project at Archlinux, jdk19, Flutter - 3.11.0-2.0.pre.83

### ISSUE THREAD

**Issue by dG94Cg** [Tensegritics/ClojureDart#226]
# Can't Compile Sample Project By clj -M:cljd compile 

## Error Show
```
Compiling cljd.core to Dart
Unhandled exception:
Exception: Missing implementation of visitTypeAliasElementImpl
#0      ThrowingElementVisitor._throw (package:analyzer/dart/element/visitor.dart:584:5)
#1      ThrowingElementVisitor.visitTypeAliasElement (package:analyzer/dart/element/visitor.dart:578:57)
#2      TypeAliasElementImpl.accept (package:analyzer/src/dart/element/element.dart:6051:20)
#3      retrieveElement (file:///home/wulianlei/hello/.clojuredart/cache/81dd5f73285b06fa8904076e3299ee8feff101df/cljd_helper/bin/analyzer.dart:415:19)
<asynchronous suspension>
#4      main (file:///home/wulianlei/hello/.clojuredart/cache/81dd5f73285b06fa8904076e3299ee8feff101df/cljd_helper/bin/analyzer.dart:368:13)
<asynchronous suspension>
```
thing happens at executing
 `clj -M:cljd compile`.

## Project Directory Show
there is only 
```edn
{:paths ["src"] ; where your cljd files are
 :deps {tensegritics/clojuredart
        {:git/url "https://github.com/tensegritics/ClojureDart.git"
         :sha "81dd5f73285b06fa8904076e3299ee8feff101df"}}
 :aliases {:cljd {:main-opts ["-m" "cljd.build"]}}
 :cljd/opts {:kind :flutter
             :main acme.main}}
```

### Sdk Version

ClojureDart Git Version: d5203b344f186c25bed8705a4dffca5b2396faa8
Flutter SDK:
> Flutter 3.11.0-2.0.pre.83 • channel master • https://github.com/flutter/flutter.git
> Framework • revision 8ab782d08a (6 hours ago) • 2023-05-09 17:50:11 -0700
> Engine • revision 8ca16cba8c
> Tools • Dart 3.1.0 (build 3.1.0-89.0.dev) • DevTools 2.23.1

> PS: confusing with why the sample project can't work, should i use some specify tag of ClojureDart?

**Comment by dupuchba** [comment]
hey @dG94Cg , thanks for the report but we don't support Dart 3.x yet which is not officially released yet. There is a PR that should be finished soon on the 3.x support.
Can you try again but with Dart 2.X
?

**Comment by cgrand** [comment]
@dG94Cg In other words: user Flutter stable channel.

**Comment by dG94Cg** [comment]
@cgrand @dupuchba thanks, i have switch the Flutter Version into [3.7.12](https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.7.12-stable.zip)

> According To: https://docs.flutter.dev/release/archive

** IT WORK NOW**
