### ISSUE TITLE
`use-fixtures :each` doesn't seem to work

### ISSUE THREAD

**Issue by valerauko** [Tensegritics/ClojureDart#242]
In a test namespace when I try to use (at the top level of the namespace, outside of any `deftest` or `testing`) `(use-fixtures :each reset-state)` where `reset-state` is a function defined in the same ns, I get an error saying `Can't call setUpAll() once tests have begun running`.

`use-fixtures :once` works just fine.

**Comment by dupuchba** [comment]
maybe we can close this one right @valerauko ?

**Comment by valerauko** [comment]
@dupuchba definitely! The pr is already marked to close this issue when merged.

I've adjusted tests as you suggested. Is there anything else?
