### ISSUE TITLE
dart analyze friendly generated code

### ISSUE THREAD

**Issue by valerauko** [Tensegritics/ClojureDart#251]
The code output by cljd compile at this point, when passed through dart analyze, result in a ton of warnings. Would it be possible to adjust the code generation to align better with standard dart analyze coding guidelines?

**Comment by valerauko** [comment]
Examples

## Warnings
* The value of the local variable 'context$9656_$AUTO_$1' isn't used. Try removing the variable or using it.
* Unused import: '../../state/manual.dart'. Try removing the import directive.
  * this seems to happen when a namespace is required but only used as an alias for keywords
* Unused import: '../cljd/core.dart'. Try removing the import directive.
  * interestingly in super simple namespaces it seems cljd isn't needed? I got this warning in a namespace that contains one defn that builds a material widget without using any clojure functions
  * I also get a warning in the same namespace about importing itself (eg in a widget.cljd I get a Unused import: 'widget.dart' warning)
* The value of the local variable '$UNDERSCORE_$2' isn't used. Try removing the variable or using it.
  * it's meant to be unused -- is there a way to work around this?
* Unnecessary type check; the result is always 'true'. Try correcting the type check, or removing the type check.
  * there's a lot of these
  * one corresponding generated code is `if((o7855$1 is lcoc_core.ILookup$iface)){`
* The label '_default' isn't used. Try removing the label, or using it in either a 'break' or 'continue' statement.
* Tests for null should be done with '== null'. Try replacing the 'is Null' check with '== null'.
* The exception variable 'e$1' isn't used, so the 'catch' clause can be removed. Try removing the catch clause.

## Notes
* The variable name '$_lookup$2' isn't a lowerCamelCase identifier. Try changing the name to follow the lowerCamelCase style.
* The member '$_lookup$2' overrides an inherited member but isn't annotated with '@OverRide'. Try adding the '@OverRide' annotation.
* Unnecessary cast. Try removing the cast.
  * corresponding generated code from cljd.core: `final dc.int k$2=((k$1 as dc.num).toInt());`
* The type name '$C$dc$DOT_List$$lcoc_core$DOT_ILookup$D$$cext' isn't an UpperCamelCase identifier. Try changing the name to follow the UpperCamelCase style.

**Comment by cgrand** [comment]
All these warnings are purely stylistic: I bet that most if not all have no impact on generated code.

May take would be that we exclude `clad-out` from analysis see https://dart.dev/tools/analysis

**Comment by valerauko** [comment]
I agree wrt the stylistic suggestions (like CamelCase).

Do you know of a way to blanket disable the linter in the analysis_options.yaml? The best I could come up with at this point was adding `// ignore_for_file: type=lint` as the first line to every generated dart file in cljd-out.

After adding that, only a few issues remain:
* unnecessary_type_check
* unused_local_variable
* unused_label
* unnecessary_null_comparison

These are analyzer errors. I don't know if they have any influence on app performance (considering the analyzer detects it I'd assume the dart compiler to eliminate them), but if it's not something you're interested fixing in ClojureDart, maybe it'd be good to ignore them in the analysis_options.yaml generated from a cljd template?

**Comment by dupuchba** [comment]
@valerauko last commit fixes this, it should silence everything
