### ISSUE TITLE
ffi sample

### ISSUE THREAD

**Issue by anatoly62** [Tensegritics/ClojureDart#274]
How to lookup function with arguments?

**Comment by TiLogic** [comment]
I don't have a `ClojureDart` example for you, but a `Dart` example of functions with arguments can be found [here](https://github.com/dart-lang/ffigen/blob/main/example/simple/generated_bindings.dart).

You might be interested in the [ffigen package](https://pub.dev/packages/ffigen). Which parses `C` header files and generates a `Dart` API, which you can then call from `ClojureDart`. It's much easier than writing it manually.

**Comment by anatoly62** [comment]
Thanks, I see that, but an ClojureDart example is needed.

**Comment by dupuchba** [comment]
hello @anatoly62  & @TiLogic - there is an example of simple ffi in the repo, using ffigen in cljd is no different from Dart itself. Thanks for the suggestion to make a new sample for ffigen, I'll try to do it this week.
We're also preparing the next newsletter release and it'll be on ffi & ffigen. Should be out next week. Thanks for your support

**Comment by dupuchba** [comment]
back to your problem @anatoly62 - here is a full example with ffigen.
https://github.com/Tensegritics/ClojureDart/tree/main/samples/fficjson
Don't hesitate to ask questions on the channel if you need to
