### ISSUE TITLE
Application launch for 'com.example.hello' did not return a valid pid nor a launch error.

### ISSUE THREAD

**Issue by DarrellBrogdon** [Tensegritics/ClojureDart#31]
I get the following error when trying to run the "hello" Flutter app:

```
[18:53:10 hello]$ open -a Simulator
[18:53:16 hello]$ clj -M -m cljd.build flutter
Warming up `.clojuredart/libs-info.edn` (helps us emit better code)

Compiling cljd.core to Dart
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Compiling to Dart... @18:53
  acme.main
  I like when a plan comes together! 👨‍🦳

Lauching flutter run
Launching lib/main.dart on iPhone 13 mini in debug mode...
Running Xcode build...
Xcode build done.                                            5.3s
Exception: Unable to launch com.example.hello on 8A799269-CB24-4E68-9644-D7CD91CFEAF1:
ProcessException: Process exited abnormally:
com.example.hello: 0

An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Application launch for 'com.example.hello' did not return a valid pid nor a launch error.
No such process
  Command: /usr/bin/arch -arm64e xcrun simctl launch 8A799269-CB24-4E68-9644-D7CD91CFEAF1 com.example.hello --enable-dart-profiling --enable-checked-mode --verify-entry-points
  --observatory-port=0
Error launching application on iPhone 13 mini.

Exception in thread "Thread-10" java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445)
	at java.base/java.io.OutputStream.write(OutputStream.java:162)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:320)
	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:160)
	at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:248)
	at cljd.build$compile_cli$fn__6683.invoke(build.clj:225)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

This is on a 16" 2021 MacBook Pro running macOS Monterrey Version 12.3.1 (21E258) and Xcode Version 13.3.1 (13E500a)

**Comment by cgrand** [comment]
Can you provide us with the whole project directory?

**Comment by dupuchba** [comment]
It's probably an Xcode error, can you try to `open ios/Runner.xcworkspace/` and run the application (don't forget to check your certificates).
If it works, you should be able to relaunch everything using ClojureDart

**Comment by DarrellBrogdon** [comment]
Running in Xcode didn't work.

The full directory can be downloaded from here: https://drive.google.com/file/d/1X0upfFTx1fSGijmLFkI9xScS_zOPLAsP/view?usp=sharing

**Comment by dupuchba** [comment]
I took your zip and launch a simulator with `open -a Simulator` and then I ran `flutter run` and it worked perfectly.
![image](https://user-images.githubusercontent.com/911705/164391666-56d1a17d-2396-4522-8551-f6cf603ba170.png)
I am pretty sure it's an Xcode configuration issue.
Try `flutter clean` 
and then `flutter pub get` and `flutter run`
Also open Xcode with `open ios/Runner.xcwordspace/` and try to fix the signing informations 
![image](https://user-images.githubusercontent.com/911705/164392016-7c1c719b-3490-42e4-9c0c-37f5a36bc525.png)

**Comment by DarrellBrogdon** [comment]
Thank you.  Turns out the problem was with the iOS Simulator: https://stackoverflow.com/questions/71838645/flutter-app-not-launching-on-simulator-it-exits-because-of-not-return-a-valid

A simple restart of the Simulator resolves the problem.
