### ISSUE TITLE
const for named constructor

### ISSUE THREAD

**Issue by ampersanda** [Tensegritics/ClojureDart#53]
## Description
Allow adding `^:const` for named constructor call/factory

## Problem
`--dart-define` variables that could be get from `(String/fromEnvirontment "KEY")` returns empty string instead of original content because of flutter this issue https://github.com/flutter/flutter/issues/55870. Allowing `const` when declaring will solve this.

I tried 
```clj
(def ^:const key (String/fromEnvirontment "KEY"))
```

but the compiler seems to ignore the const meta

Slack - https://clojurians.slack.com/archives/C03A6GE8D32/p1651606676187039

**Comment by cgrand** [comment]
Fixed. `:const` meta must go on the constructor form `^:const (String/fromEnvirontment "KEY")`
