### ISSUE TITLE
cycle in libs, StackOverflowError

### ISSUE THREAD

**Issue by Liverm0r** [Tensegritics/ClojureDart#64]
To reproduce, just add this dependency in any cljd project: https://pub.dev/packages/bip32_ed25519.

`bip32_ed25519: ^0.2.1`.

I reproduced it in a just created fresh project. No libs-info even generated. 

Here is a libs-info from another project where I have encountered it. 53k lines.
[libs-info.edn.zip](https://github.com/Tensegritics/ClojureDart/files/8689643/libs-info.edn.zip)

**Comment by dupuchba** [comment]
Did not know it was possible but 2 files exports themselves : 
in [bip32-ed25519-dart](https://github.com/ilap/bip32-ed25519-dart)/[lib](https://github.com/ilap/bip32-ed25519-dart/tree/master/lib)/bip32_ed25519.dart
```dart
library bip32_ed25519;

export 'package:bip32_ed25519/api.dart';
export 'package:bip32_ed25519/src/bip32_ed25519/ed25519_extended.dart';
export 'package:bip32_ed25519/src/bip32_ed25519/ed25519_bip32.dart';
```

and then in [bip32-ed25519-dart](https://github.com/ilap/bip32-ed25519-dart)/[lib](https://github.com/ilap/bip32-ed25519-dart/tree/master/lib)/api.dart`
```dart
library bip32_ed25519.api;

import 'package:pinenacl/api.dart';

export 'dart:typed_data';
export 'package:pinenacl/ed25519.dart';
export 'package:bip32_ed25519/bip32_ed25519.dart';

/// BIPs
part 'package:bip32_ed25519/src/api/bip32.dart';
part 'package:bip32_ed25519/src/api/bip43.dart';
part 'package:bip32_ed25519/src/api/bip44.dart';
part 'package:bip32_ed25519/src/cardano/api/cip1852.dart';
part 'package:bip32_ed25519/src/cardano/api/cip1854.dart';
```

**Comment by dupuchba** [comment]
fixed https://github.com/Tensegritics/ClojureDart/commit/e1f6cf7740b0e6fff42e48b51f384181d2627765
