### ISSUE TITLE
Mutation not happening for a deftype

### ISSUE THREAD

**Issue by pfeodrippe** [Tensegritics/ClojureDart#66]
I'm running the code below and I would expect `{:v 40}` as the output.

```clojure
(ns quickstart.helloworld)

(defprotocol ITestProtocol
  (act [_ _]))

(deftype Test [^:mutable x-a]
  ITestProtocol
  (act [this o] (set! x-a o))

  Object
  (toString [this]
    (str x-a)))

(def t (Test. 10))
(act t 40)

(defn main []
  (print {:v t}))
```

But I'm having

```clojure
{:v 10}
```

When I move `(act t 40)` to main, I have the following error
```clojure
Unhandled exception:
Exception: No extension of protocol ITestProtocol found for type int.
#0      ITestProtocol$iprot.extensions (file:///Users/paulo.feodrippe/dev/dartapp/lib/cljd-out/quickstart/helloworld.dart:47:1)
#1      main (file:///Users/paulo.feodrippe/dev/dartapp/lib/cljd-out/quickstart/helloworld.dart:97:37)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

**Comment by cgrand** [comment]
Top level mutation is not supported. 

Now the (act t 40) in the main should work. I think the problem comes from the (act _ _) declaration. Please try with distinct parameter names.

**Comment by pfeodrippe** [comment]
> ```clojure
> (defprotocol ITestProtocol
>   (act [_ _]))
> 
> (deftype Test [^:mutable x-a]
>   ITestProtocol
>   (act [this o] (set! x-a o))
> 
>   Object
>   (toString [this]
>     (str x-a)))
> 
> (def t (Test. 10))
> (act t 40)
> 
> (defn main []
>   (print {:v t}))
> ```

Nice thanks!!
