### ISSUE TITLE
pubspec.yaml in cljd.edn: unify configuration file

### ISSUE THREAD

**Issue by avelino** [Tensegritics/ClojureDart#90]
Instead of having to maintain several configuration files, why not keep as much configuration as possible in `cljd.edn`?

Automatically generating `pubspec.yaml` at runtime

**Comment by avelino** [comment]
To make an application using ClojureDart you have 3 configuration files:
- `deps.edn` clojure config
- `cljd.edn` clojuredart config
- `pubspec.yaml` flutter app config

My proposal would be to unify them all into a single file, for example `cljd.edn` or `deps.edn` (as is done in Node which uses [package.json](https://docs.npmjs.com/cli/v8/configuring-npm/package-json)).

Inside the package.json we have the package publication configuration, dependencies, authors and etc.

**example `cljd.edn`:**
```edn
{;; cljd.edn
 :flutter {:main example.main, :bin "flutter"}
 
 ;; deps.edn
 :paths ["src"]
 :deps {org.clojure/clojure {:mvn/version "1.10.1"}
        tensegritics/clojuredart
        {:git/url "git@github.com:tensegritics/ClojureDart.git"
         :sha "b49677deaee9c2cc46c165975004d297fe5cabc8"}}

 ;; pubspec.yaml
 :pub {:name "example"
       :description "A new Flutter project."
       :publish_to "none"
       :version "1.0.0"
       :environment {:sdk ">=2.16.2 <3.0.0"}
       :dependencies {:flutter {:sdk "flutter"}
                      :cupertino_icons {:version "^1.0.2"}}
       :flutter {:uses-material-design true}}}
```

Running `cljd.build` reads `cljd.edn` and generates the necessary files in memory (or disk), so that when the process is stopped we remove the files if they were created by `cljd.build`
```sh
clj -M -m cljd.build flutter
```

**Comment by cgrand** [comment]
This makes working with flutter cli for adding packages etc impossible and we need to map into edn much if not all of pub spec.yaml.
Nice idea but costs/benefits not compelling at the moment.
