### ISSUE TITLE
stateful widget calls dispose on FocusNode but state still there

### ISSUE THREAD

**Issue by dupuchba** [Tensegritics/ClojureDart#99]
*Edge case*
**note that it's not a bug but we'd like to improve user XP when this happens**

Repro : 
1/ having some kind of `StreamBuilder` with firebase for example
```clj
(m/StreamBuilder
      :stream stream
      :builder
      (fn [_ snapshot]
        (let [connection-state (.-connectionState snapshot)]
          (if (or
                (== connection-state m.ConnectionState/none)
                (== connection-state m.ConnectionState/waiting))
            login
            (if (== connection-state m.ConnectionState/done)
              
              (m/Text "Don't know what to do here")
              (if-some [user (.-data snapshot)]
                main-app
                login))))))
```
2/ then your login is a stateful widget with focus-node and a `TextField` for example
```clj
(f/widget
     
     :with [focus-node-email (m/FocusNode)
            focus-node-password (m/FocusNode)])
```
3/ dispose will be call but focus-node will still be used after-all creating a sucky exception

Temporary solution : 
wrap the stateful widget in a stateless one `(f/widget my-stateful-widget)`

**Comment by cgrand** [comment]
Can you make a self contained runnable minimal repro?

**Comment by cgrand** [comment]
`(def my-widget (f/widget ...))` of stateful widgets seems to be problematic.

**Comment by dupuchba** [comment]
At that time I was mislead, it's not a state problem but it's how we update streams
